## selenium project for job info

In [1]:
# our objective is to utilize selenium using ython to collect and scrape hiring infro from wuzzuf.com

In [2]:
#1-lets start by importing our librares that we will need to make this project.
import selenium # this is our main library that we are going to use for automation and web scrapping
import time # we will use the time library to allow smooth transitions between the website pages 
from selenium import webdriver
from selenium.webdriver.common.by import By 
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager # we will be using chrome for our project

In [3]:
#2-lets save our url in a summerized way to keep a simplistic look.
URL= "https://wuzzuf.net/"

In [4]:
#3- we are going to be using these options just to avoid the bot detection system.
options = Options()
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)
#options.add_argument("--headless=new") # we can use this at the very end to make our process seamless, lets save that for later
options.add_argument("--window-size=1920,1080")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

In [ ]:
# we are going to be searching for info about the following jobs:
#Data Engineer
#Data Science 
#AI Developer
#Machine Learning Engineer

In [ ]:
#4- lets start making selenium open our website. 
driver = webdriver.Chrome()
driver.get(URL)
time.sleep(10)#--> to allow our website some time to load 
driver.quit()

In [ ]:
#5-now lets make selenium start inputing our search data and have it click search.
driver = webdriver.Chrome()
driver.get(URL)
time.sleep(1)
driver.find_element(By.NAME,"q").send_keys("Data Engineer")#--> we here used the name of the search bar to lock onto it and input out first job
time.sleep(1)
driver.find_element(By.CLASS_NAME,"css-1stvrxn").click()#--> we found the class name for the search button
time.sleep(2)
driver.refresh()#--> we are going to be refreshing to avoid the app interface blocking selenium
time.sleep(10)
driver.quit()

In [ ]:
#6- here we are just going to be making a list to store our data temporarily 
list_of_job_info=[]

In [ ]:
#7-here we are going to start collecting data from the first page of our first job 
driver = webdriver.Chrome()
driver.get(URL)
time.sleep(1)
driver.find_element(By.NAME,"q").send_keys("Data Engineer")
time.sleep(1)
driver.find_element(By.CLASS_NAME,"css-1stvrxn").click()
time.sleep(2)
driver.refresh()
time.sleep(10)
###-----------lets make a small loop that goes over every job
jobs = driver.find_elements(By.CLASS_NAME,"css-ghe2tq")#class name for every job card 
for job in jobs:
    Job_title = job.find_element(By.CLASS_NAME,"css-o171kl").text
    Company=job.find_element(By.CLASS_NAME,"css-ipsyv7").text
    Location=job.find_element(By.CLASS_NAME,"css-16x61xq").text
    Job_Type=job.find_element(By.CLASS_NAME,"css-uc9rga").text
    Job_URL=job.find_element(By.CLASS_NAME,"css-o171kl").get_attribute("href")#--> since link doesnt have class we can use its attribute  

    list_of_job_info.append({
        "Job_title":Job_title,
        "Company":Company,
        "Location":Location,
        "Job_Type":Job_Type,
        "Job_URL":Job_URL
    })
time.sleep(10)
driver.quit()

In [ ]:
#8- now we are going to make selenium go over multiple pages 
driver = webdriver.Chrome()
driver.get(URL)
time.sleep(1)
driver.find_element(By.NAME,"q").send_keys("Data Engineer")
time.sleep(1)
driver.find_element(By.CLASS_NAME,"css-1stvrxn").click()
time.sleep(2)
driver.refresh()
time.sleep(10)
list_of_jobs = []
for i in range (2):
  jobs = driver.find_elements(By.CLASS_NAME,"css-ghe2tq")#outer loop to check first 3 pages 
  time.sleep(5)
  for job in jobs:
     Job_title = job.find_element(By.CLASS_NAME,"css-o171kl").text
     Company=job.find_element(By.CLASS_NAME,"css-ipsyv7").text
     Location=job.find_element(By.CLASS_NAME,"css-16x61xq").text
     Job_Type=job.find_element(By.CLASS_NAME,"css-uc9rga").text
     Job_URL=job.find_element(By.CLASS_NAME,"css-o171kl").get_attribute("href")

     list_of_job_info.append({
        "Job_title":Job_title,
        "Company":Company,
        "Location":Location,
        "Job_Type":Job_Type,
        "Job_URL":Job_URL
      })
  try:
     driver.find_element(By.CSS_SELECTOR, "button[class='css-kefogq ezfki8j0']").click()#clicking on next page button 
     time.sleep(3)
  except:
      break


time.sleep(10)
driver.quit()

In [8]:
#9-now lets loop around multiple job searches
import pandas as pd 
positions = ['Ai Developer', 'Data Analyst', 'Data Scientist', 'Data Engineer'] 
 
options = Options() 
options.add_argument("--disable-blink-features=AutomationControlled") 
options.add_experimental_option("excludeSwitches", ["enable-automation"]) 
options.add_experimental_option('useAutomationExtension', False) 
#options.add_argument("--headless=new") # we can use this at the very end to make our process seamless, lets save that for later 
options.add_argument("--window-size=1920,1080") 
options.add_argument("--disable-gpu") 
options.add_argument("--no-sandbox") 
options.add_argument("--disable-dev-shm-usage") 
driver = webdriver.Chrome(options=options) 
driver.get(URL) 
list_of_job_info= [] 

for position in positions: 

    time.sleep(2) 
    driver.find_element(By.NAME,"q").send_keys(position) 
 
    driver.find_element(By.XPATH, "//button[@type='submit']").click() 
 
    time.sleep(2) 
 
    driver.refresh() 
 
    time.sleep(7) 
 
    for i in range(5): 

        time.sleep(3) 
        jobs = driver.find_elements(By.CLASS_NAME,"css-ghe2tq") # outer loop to check first 5 pages
        time.sleep(1) 

        for job in jobs: 

            Job_title = job.find_element(By.CLASS_NAME,"css-o171kl").text 
            Company = job.find_element(By.CLASS_NAME,"css-ipsyv7").text 
            Location = job.find_element(By.CLASS_NAME,"css-16x61xq").text 
            Job_Type = job.find_element(By.CLASS_NAME,"css-uc9rga").text 
            Job_URL = job.find_element(By.CLASS_NAME,"css-o171kl").get_attribute("href"), 

            try: 
                job_exp = job.find_element(
                    By.CSS_SELECTOR, 
                    "div > div.css-1rhj4yg > div:nth-child(2) > span"
                ).text 

            except: 
                job_exp = '' ,

            job_occupation = job.find_element(By.CLASS_NAME,"css-uofntu").text 
 
            list_of_job_info.append({ 
                "Job_title":Job_title, 
                "Company":Company, 
                "Location":Location, 
                "Job_Type":Job_Type, 
                "Job_URL":Job_URL, 
                "Job Experience":job_exp, 
                "job occupation":job_occupation  
            }) 

            time.sleep(1) 

        # NEXT PAGE happens AFTER collecting all jobs on the current page
        try: 
                           next_button = driver.find_element(
                               By.XPATH, "(//*[contains(@class, 'css-kefogq')])[last()]"# here we can observe some new syntax since we have two buttons with the same class we need to have a work around for it 
                           )# we are just finding the element and adding last to it bec its the next button thatbwe wanna Click  on and not the back button 
                           next_button.click()
                           time.sleep(5)  
        except: 
                break 
 
df = pd.DataFrame(list_of_job_info)

In [9]:
list_of_job_info

[{'Job_title': 'Software Development Intern – Full-Stack & AI',
  'Company': 'Sherkety -',
  'Location': 'Alexandria, Egypt',
  'Job_Type': 'Internship',
  'Job_URL': ('https://wuzzuf.net/internship/rn5qmqxnv4w5-software-development-intern-full-stack-ai-sherkety-alexandria-egypt',),
  'Job Experience': '· 0 - 1 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Full Stack .NET Developer – AI-Assisted Development',
  'Company': 'Roaya -',
  'Location': 'Maadi, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/l7avtmywmfxg-full-stack-net-developer-ai-assisted-development-roaya-cairo-egypt',),
  'Job Experience': '· 0 - 1 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'AI & API Integration Developer (Full-Time, Remote)',
  'Company': 'iBrokerage Ltd. -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/izzdd2byxhfw-ai-api-integration-developer-full-time-remote-ibrokerage-ltd-cairo-egypt',),
  'Job Experience': '· 3 - 5 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Senior AI / Backend Engineer – Technical Lead (SaaS)',
  'Company': 'Confidential -',
  'Location': 'Kuwait City, Kuwait',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/eghcexks7ptv-senior-ai-backend-engineer-technical-lead-saas-kuwait-city-kuwait',),
  'Job Experience': '· 5 - 10 Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'AI & Business Process Transformation Manager',
  'Company': 'Luxury Hospitality -',
  'Location': '6th of October, Giza, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/7odmfeuocw2j-ai-business-process-transformation-manager-luxury-hospitality-giza-egypt',),
  'Job Experience': '· 3 - 7 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Senior AI & Software Engineer',
  'Company': 'The-Code -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/3sknscktm5if-senior-ai-software-engineer-the-code-cairo-egypt',),
  'Job Experience': '· 5 - 7 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'AI Engineer',
  'Company': 'Confidential -',
  'Location': 'Sheraton, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/kca9wrw4ul4l-ai-engineer-cairo-egypt',),
  'Job Experience': '· 3 - 4 Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'Middle Full-Stack (PHP) - AI Expertise',
  'Company': 'Vertex Technologies -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/yqpqphojdzwj-middle-full-stack-php-ai-expertise-vertex-technologies-cairo-egypt',),
  'Job Experience': '· 2+ Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'AI Engineer (LLM & AI Applications)',
  'Company': 'Exab -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/f3fqbcncr7i6-ai-engineer-llm-ai-applications-exab-cairo-egypt',),
  'Job Experience': '· 3 - 7 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Junior AI Technology Engineer',
  'Company': 'Investia Venture Capital -',
  'Location': 'New Cairo, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/gv1msetmo0bw-junior-ai-technology-engineer-investia-venture-capital-cairo-egypt',),
  'Job Experience': '· 3 - 7 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'AI-Powered Full-Stack Developer',
  'Company': 'TAB ERP Solutions -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/hbruwzefkcn0-ai-powered-full-stack-developer-tab-erp-solutions-cairo-egypt',),
  'Job Experience': '· 2 - 4 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'B2B Sales Specialist – Enterprise AI & Learning Solutions',
  'Company': 'EpsilonAI -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/gmkmvjt2c3cw-b2b-sales-specialist-enterprise-ai-learning-solutions-epsilonai-cairo-egypt',),
  'Job Experience': '· 1 - 4 Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'Telesales Executive – AI Solutions & Education',
  'Company': 'EpsilonAI -',
  'Location': 'Nasr City, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/ifvsclqhpw2t-telesales-executive-ai-solutions-education-epsilonai-cairo-egypt',),
  'Job Experience': '· 1 - 4 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'AI Engineer',
  'Company': 'Customer Audiences LLC -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/cl7sairyxznk-ai-engineer-customer-audiences-llc-cairo-egypt',),
  'Job Experience': '· 5 - 10 Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'AI Coach',
  'Company': 'DryvSmart -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/dthvvomnok6i-ai-coach-dryvsmart-cairo-egypt',),
  'Job Experience': '· 4+ Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'Director, AI & Data CoE',
  'Company': 'PULSE -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/3yd6fw6zovno-director-ai-data-coe-pulse-cairo-egypt',),
  'Job Experience': '· 10+ Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'AI Full-Stack Developer / AI Engineer',
  'Company': 'Confidential -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/rnyj8lf7jlzj-ai-full-stack-developer-ai-engineer-cairo-egypt',),
  'Job Experience': '· 1 - 2 Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'AI Fashion & Textile Content Creator',
  'Company': 'El Chourbagi -',
  'Location': 'Heliopolis, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/pxtsg5lwrq8i-ai-fashion-textile-content-creator-el-chourbagi-cairo-egypt',),
  'Job Experience': '· 3 - 5 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Senior AI Engineer',
  'Company': 'Efada Technology -',
  'Location': 'New Cairo, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/e24mgm9chl4v-senior-ai-engineer-efada-technology-cairo-egypt',),
  'Job Experience': '· 4+ Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'AI Software Engineer – Freelance | Remote',
  'Company': 'Confidential -',
  'Location': 'Dubai, United Arab Emirates',
  'Job_Type': 'Freelance / Project',
  'Job_URL': ('https://wuzzuf.net/jobs/p/lrw7rdbrozys-ai-software-engineer-freelance-remote-dubai-united-arab-emirates',),
  'Job Experience': '· 0 - 2 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'AI Specialist',
  'Company': 'EMIRATES BARQ -',
  'Location': 'Sharjah, United Arab Emirates',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/iwb6n9erw9um-ai-specialist-emirates-barq-alshark-alamarat-alaarby-almthd',),
  'Job Experience': '· 3 - 7 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'AI Video Production',
  'Company': 'Engineeius -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Freelance / Project',
  'Job_URL': ('https://wuzzuf.net/jobs/p/reb7hiksiwdr-ai-video-production-engineeius-cairo-egypt',),
  'Job Experience': '· 2+ Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Business Development Assistant',
  'Company': 'Esnad Solutions Environmental Consulting -',
  'Location': 'Riyadh, Saudi Arabia',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/saudi/jobs/p/yj6jvpwgotul-business-development-assistant-esnad-solutions-environmental-consulting-riyadh-saudi-arabia',),
  'Job Experience': '· 0 - 2 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Data Scientist – Machine Learning & Generative AI',
  'Company': 'EpsilonAI -',
  'Location': 'Nasr City, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/ygbb8ah3zfkh-data-scientist-machine-learning-generative-ai-epsilonai-cairo-egypt',),
  'Job Experience': '· 1 - 4 Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'Senior AI Machine Learning Engineer',
  'Company': 'Techsa -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/vu52uzynigyg-senior-ai-machine-learning-engineer-techsa-cairo-egypt',),
  'Job Experience': '· 3+ Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Full-Stack Engineer (Django & Next.js)',
  'Company': 'Confidential -',
  'Location': 'Dubai, United Arab Emirates',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/yvlbdib01vhh-full-stack-engineer-django-nextjs-dubai-united-arab-emirates',),
  'Job Experience': '· 3 - 7 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Export Manager (Herbs) - Fayoum',
  'Company': 'البدر للإستيراد والتصدير -',
  'Location': 'Fayoum, Fayoum, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/sx5rpsweaeod-export-manager-herbs-fayoum-albdr-llastyrad-oaltsdyr-fayoum-egypt',),
  'Job Experience': '· 10+ Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'B2B Membership Growth & Sales Specialist – AI-Powered Content & Digital Outreach',
  'Company': 'Confidential -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/odlwjg0ccz2g-b2b-membership-growth-sales-specialist-ai-powered-content-digital-outreach-cairo-egypt',),
  'Job Experience': '· 5+ Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'General Manager',
  'Company': 'Confidential -',
  'Location': 'Nasr City, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/3rtunlr39o7o-general-manager-cairo-egypt',),
  'Job Experience': '· 15 - 20 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Podcast Host (English)',
  'Company': 'InboxRev -',
  'Location': 'Austin, United States',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/mcp3ksxi3dng-podcast-host-english-inboxrev-austin-united-states',),
  'Job Experience': '· 1 - 2 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'AI / Machine Learning Engineer',
  'Company': 'Confidential -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/nsgeozvz1sas-ai-machine-learning-engineer-cairo-egypt',),
  'Job Experience': '· 3 - 7 Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'AI Engineer',
  'Company': 'Midas Global Tech -',
  'Location': 'Shubra, Cairo, Egypt',
  'Job_Type': 'Part Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/ngu4glqj8nbv-ai-engineer-midas-global-tech-cairo-egypt',),
  'Job Experience': '· 5+ Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Senior Data Scientist',
  'Company': 'Vertex Technologies -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/yzal3d0v861d-senior-data-scientist-vertex-technologies-cairo-egypt',),
  'Job Experience': '· 5+ Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Academic & IT Curriculum Director',
  'Company': 'MICA -',
  'Location': 'Haram, Giza, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/vtco6sgxfjd7-academic-it-curriculum-director-mica-giza-egypt',),
  'Job Experience': '· 8 - 20 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'AI Engineer',
  'Company': 'ITGoals -',
  'Location': 'New Cairo, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/obuc0novnoqj-ai-engineer-itgoals-cairo-egypt',),
  'Job Experience': '· 3 - 7 Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'Embedded Systems & AI Instructor',
  'Company': 'MICA -',
  'Location': 'Haram, Giza, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/zpbuc7jbk256-embedded-systems-ai-instructor-mica-giza-egypt',),
  'Job Experience': '· 0 - 2 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Associate Product Manager (Engineering Background)',
  'Company': 'Menthum -',
  'Location': 'Maadi, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/q6qo9fkpy5ac-associate-product-manager-engineering-background-menthum-cairo-egypt',),
  'Job Experience': '· 2 - 5 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Islamic Content Creator',
  'Company': 'Consultraining Inc. -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/nbhyqzmxeamf-islamic-content-creator-consultraining-inc-cairo-egypt',),
  'Job Experience': '· 1 - 5 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Fashion Designer',
  'Company': 'Confidential -',
  'Location': 'Obour City, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/9byvlyad3wso-fashion-designer-cairo-egypt',),
  'Job Experience': '· 3 - 5 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'senior graphic designer',
  'Company': 'Cairbou Coffee Egypt -',
  'Location': 'Maadi, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/i5caf3talmru-senior-graphic-designer-cairbou-coffee-egypt-cairo-egypt',),
  'Job Experience': '· 3 - 5 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Marketing Executive',
  'Company': 'Confidential -',
  'Location': 'Giza, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/vle5dgxuvjka-marketing-executive-giza-egypt',),
  'Job Experience': '· 2 - 4 Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'SME Science Specialist',
  'Company': 'Nahdet Misr Publishing Group -',
  'Location': 'Mohandessin, Giza, Egypt',
  'Job_Type': 'Internship',
  'Job_URL': ('https://wuzzuf.net/internship/l5lgypkj5nm5-sme-science-specialist-nahdet-misr-publishing-group-giza-egypt',),
  'Job Experience': ('',),
  'job occupation': 'On-site'},
 {'Job_title': 'Part-Time Carpet Designer – Fully Remote',
  'Company': 'Carpetivity -',
  'Location': '10th of Ramadan City, Sharqia, Egypt',
  'Job_Type': 'Part Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/mqomzksiv7vd-part-time-carpet-designer-fully-remote-carpetivity-sharqia-egypt',),
  'Job Experience': '· 3 - 7 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Graphic & Motion Designer',
  'Company': 'Carofi -',
  'Location': 'New Cairo, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/lc4lsr5emf6u-graphic-motion-designer-carofi-cairo-egypt',),
  'Job Experience': '· 3 - 5 Yrs of Exp',
  'job occupation': 'Hybrid'},
 {'Job_title': 'Mechanical Maintenance Engineer',
  'Company': 'Joy Glass -',
  'Location': '6th of October, Giza, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/xvyondl2pwlx-mechanical-maintenance-engineer-joy-glass-giza-egypt',),
  'Job Experience': '· 1 - 3 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Trainee iOS Developer',
  'Company': 'Vertex Technologies -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/zfsocxppmtxk-trainee-ios-developer-vertex-technologies-cairo-egypt',),
  'Job Experience': '· 0 - 2 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Middle Android Developer.',
  'Company': 'Vertex Technologies -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/kgl5zdufwv0c-middle-android-developer-vertex-technologies-cairo-egypt',),
  'Job Experience': '· 3+ Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Middle React Native Developer',
  'Company': 'Vertex Technologies -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/5cfcg36wbygq-middle-react-native-developer-vertex-technologies-cairo-egypt',),
  'Job Experience': '· 3+ Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Performance & Growth Marketing Specialist',
  'Company': 'Confidential -',
  'Location': 'Dubai, United Arab Emirates',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/j8qo1btscxce-performance-growth-marketing-specialist-dubai-united-arab-emirates',),
  'Job Experience': '· 3 - 5 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Senior Full-Stack Engineer (Django + React + Python + GCP)',
  'Company': 'Confidential -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/lz2yes11afoc-senior-full-stack-engineer-django-react-python-gcp-cairo-egypt',),
  'Job Experience': '· 5+ Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Senior Python Developer',
  'Company': 'Nile Bits, LLC -',
  'Location': '6th of October, Giza, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/7jkhc0bc9ozg-senior-python-developer-nile-bits-llc-giza-egypt',),
  'Job Experience': '· 4 - 8 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Senior Full Stack Developer (.NET Core / Angular)',
  'Company': 'Exab -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/12x1qo2z9wu8-senior-full-stack-developer-net-core-angular-exab-cairo-egypt',),
  'Job Experience': '· 3 - 7 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Qt / QML Application Developer (C++)',
  'Company': 'Masternuts -',
  'Location': 'Obour City, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/cdfekthmbzhe-qt-qml-application-developer-c-masternuts-cairo-egypt',),
  'Job Experience': '· 1 - 7 Yrs of Exp',
  'job occupation': 'Remote'},
 {'Job_title': 'Junior Technical Support & Full-Stack Developer Intern',
  'Company': 'Advanced Mowasl For Information Technology -',
  'Location': 'New Cairo, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/pw74fupm2ihn-junior-technical-support-full-stack-developer-intern-advanced-mowasl-for-information-technology-cairo-egypt',),
  'Job Experience': ('',),
  'job occupation': 'Remote'},
 {'Job_title': 'Senior Full Stack .NET Developer',
  'Company': 'Confidential -',
  'Location': 'Dokki, Giza, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/jizkzgxpax8c-senior-full-stack-net-developer-giza-egypt',),
  'Job Experience': '· 8 - 15 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Senior Video Editor / Motion Graphic Designer',
  'Company': 'Artal Egypt -',
  'Location': 'New Cairo, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/u8smuo5j7tcg-senior-video-editor-motion-graphic-designer-artal-egypt-cairo-egypt',),
  'Job Experience': '· 5 - 10 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Senior Full Stack JS Developer',
  'Company': 'Vertex Technologies -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/lzoegyxxpo8j-senior-full-stack-js-developer-vertex-technologies-cairo-egypt',),
  'Job Experience': '· 6+ Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Senior Android Developer',
  'Company': 'Vertex Technologies -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/e6gxuwvnxebp-senior-android-developer-vertex-technologies-cairo-egypt',),
  'Job Experience': '· 5 - 6 Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Senior IOS Developer.',
  'Company': 'Vertex Technologies -',
  'Location': 'Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/9ymk8acrcpe7-senior-ios-developer-vertex-technologies-cairo-egypt',),
  'Job Experience': '· 5+ Yrs of Exp',
  'job occupation': 'On-site'},
 {'Job_title': 'Graphic Designer',
  'Company': 'elbaraka -',
  'Location': 'Nasr City, Cairo, Egypt',
  'Job_Type': 'Full Time',
  'Job_URL': ('https://wuzzuf.net/jobs/p/qnelysflxcbi-graphic-designer-elbaraka-cairo-egypt',),

In [10]:
df.info

<bound method DataFrame.info of                                              Job_title  \
0        Software Development Intern – Full-Stack & AI
1    Full Stack .NET Developer – AI-Assisted Develo...
2    AI & API Integration Developer (Full-Time, Rem...
3    Senior AI / Backend Engineer – Technical Lead ...
4         AI & Business Process Transformation Manager
..                                                 ...
227               Protection Control & Scada Engineers
228                                Civil Site Engineer
229              Pre Sales Engineer - Financial Sector
230     Architect design and technical office engineer
231   Technical Support / Application Support Engineer

                                   Company                         Location  \
0                               Sherkety -                Alexandria, Egypt
1                                  Roaya -              Maadi, Cairo, Egypt
2                        iBrokerage Ltd. -                     Cairo, Egypt
3                           Confidential -              Kuwait City, Kuwait
4                     Luxury Hospitality -      6th of October, Giza, Egypt
..                                     ...                              ...
227  National Electricity Technology Co. -  Bourj Alarab, Alexandria, Egypt
228                       Eamar Al Delta -            Tanta, Gharbia, Egypt
229                         Romoze Egypt -          New Cairo, Cairo, Egypt
230              NEW JERSEY Developments -          New Cairo, Cairo, Egypt
231                              eVision -          New Cairo, Cairo, Egypt

       Job_Type                                            Job_URL  \
0    Internship  (https://wuzzuf.net/internship/rn5qmqxnv4w5-so...
1     Full Time  (https://wuzzuf.net/jobs/p/l7avtmywmfxg-full-s...
2     Full Time  (https://wuzzuf.net/jobs/p/izzdd2byxhfw-ai-api...
3     Full Time  (https://wuzzuf.net/jobs/p/eghcexks7ptv-senior...
4     Full Time  (https://wuzzuf.net/jobs/p/7odmfeuocw2j-ai-bus...
..          ...                                                ...
227   Full Time  (https://wuzzuf.net/jobs/p/iahqxidnnwwq-protec...
228   Full Time  (https://wuzzuf.net/jobs/p/lp0yz51lehcq-civil-...
229   Full Time  (https://wuzzuf.net/jobs/p/bgzruidtzqip-pre-sa...
230   Full Time  (https://wuzzuf.net/jobs/p/ifqfge4jde0i-archit...
231   Full Time  (https://wuzzuf.net/jobs/p/8xt2fry7ev52-techni...

          Job Experience job occupation
0     · 0 - 1 Yrs of Exp         Remote
1     · 0 - 1 Yrs of Exp        On-site
2     · 3 - 5 Yrs of Exp         Remote
3    · 5 - 10 Yrs of Exp         Hybrid
4     · 3 - 7 Yrs of Exp        On-site
..                   ...            ...
227   · 3 - 5 Yrs of Exp        On-site
228   · 5 - 8 Yrs of Exp        On-site
229   · 3 - 7 Yrs of Exp         Hybrid
230   · 3 - 7 Yrs of Exp        On-site
231   · 0 - 2 Yrs of Exp        On-site

[232 rows x 7 columns]>

In [11]:
df.shape

(232, 7)

In [ ]:
df.head(20)

,Job_title,Company,Location,Job_Type,Job_URL,Job Experience,job occupation
0,Software Development Intern – Full-Stack & AI,Sherkety -,"Alexandria, Egypt",Internship,(https://wuzzuf.net/internship/rn5qmqxnv4w5-so...,· 0 - 1 Yrs of Exp,Remote
1,Full Stack .NET Developer – AI-Assisted Develo...,Roaya -,"Maadi, Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/l7avtmywmfxg-full-s...,· 0 - 1 Yrs of Exp,On-site
2,"AI & API Integration Developer (Full-Time, Rem...",iBrokerage Ltd. -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/izzdd2byxhfw-ai-api...,· 3 - 5 Yrs of Exp,Remote
3,Senior AI / Backend Engineer – Technical Lead ...,Confidential -,"Kuwait City, Kuwait",Full Time,(https://wuzzuf.net/jobs/p/eghcexks7ptv-senior...,· 5 - 10 Yrs of Exp,Hybrid
4,AI & Business Process Transformation Manager,Luxury Hospitality -,"6th of October, Giza, Egypt",Full Time,(https://wuzzuf.net/jobs/p/7odmfeuocw2j-ai-bus...,· 3 - 7 Yrs of Exp,On-site
5,Senior AI & Software Engineer,The-Code -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/3sknscktm5if-senior...,· 5 - 7 Yrs of Exp,Remote
6,AI Engineer,Confidential -,"Sheraton, Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/kca9wrw4ul4l-ai-eng...,· 3 - 4 Yrs of Exp,Hybrid
7,Middle Full-Stack (PHP) - AI Expertise,Vertex Technologies -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/yqpqphojdzwj-middle...,· 2+ Yrs of Exp,On-site
8,AI Engineer (LLM & AI Applications),Exab -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/f3fqbcncr7i6-ai-eng...,· 3 - 7 Yrs of Exp,On-site
9,Junior AI Technology Engineer,Investia Venture Capital -,"New Cairo, Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/gv1msetmo0bw-junior...,· 3 - 7 Yrs of Exp,On-site
10,AI-Powered Full-Stack Developer,TAB ERP Solutions -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/hbruwzefkcn0-ai-pow...,· 2 - 4 Yrs of Exp,Remote
11,B2B Sales Specialist – Enterprise AI & Learnin...,EpsilonAI -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/gmkmvjt2c3cw-b2b-sa...,· 1 - 4 Yrs of Exp,Hybrid
12,Telesales Executive – AI Solutions & Education,EpsilonAI -,"Nasr City, Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/ifvsclqhpw2t-telesa...,· 1 - 4 Yrs of Exp,On-site
13,AI Engineer,Customer Audiences LLC -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/cl7sairyxznk-ai-eng...,· 5 - 10 Yrs of Exp,Hybrid
14,AI Coach,DryvSmart -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/dthvvomnok6i-ai-coa...,· 4+ Yrs of Exp,Hybrid
15,"Director, AI & Data CoE",PULSE -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/3yd6fw6zovno-direct...,· 10+ Yrs of Exp,On-site
16,AI Full-Stack Developer / AI Engineer,Confidential -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/rnyj8lf7jlzj-ai-ful...,· 1 - 2 Yrs of Exp,Hybrid
17,AI Fashion & Textile Content Creator,El Chourbagi -,"Heliopolis, Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/pxtsg5lwrq8i-ai-fas...,· 3 - 5 Yrs of Exp,On-site
18,Senior AI Engineer,Efada Technology -,"New Cairo, Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/e24mgm9chl4v-senior...,· 4+ Yrs of Exp,Hybrid
19,AI Software Engineer – Freelance | Remote,Confidential -,"Dubai, United Arab Emirates",Freelance / Project,(https://wuzzuf.net/jobs/p/lrw7rdbrozys-ai-sof...,· 0 - 2 Yrs of Exp,Remote

In [16]:
df.columns

Index(['Job_title', 'Company', 'Location', 'Job_Type', 'Job_URL',
       'Job Experience', 'job occupation'],
      dtype='str')

In [17]:
df.index

RangeIndex(start=0, stop=232, step=1)

In [19]:
df.describe()

,Job_title,Company,Location,Job_Type,Job_URL,Job Experience,job occupation
count,232,232,232,232,232,232,232
unique,192,138,42,4,211,53,3
top,AI Engineer,Confidential -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/ygbb8ah3zfkh-data-s...,· 3 - 7 Yrs of Exp,On-site
freq,7,33,67,218,4,34,160

In [20]:
num_duplicates = df.duplicated(subset=['Job_URL']).sum()
print(f"Number of duplicate URLs: {num_duplicates}")

Number of duplicate URLs: 21

In [22]:
df.drop_duplicates(subset=['Job_URL'], keep='first', inplace=True)
df.reset_index(drop=True, inplace=True)

In [23]:
df

,Job_title,Company,Location,Job_Type,Job_URL,Job Experience,job occupation
0,Software Development Intern – Full-Stack & AI,Sherkety -,"Alexandria, Egypt",Internship,(https://wuzzuf.net/internship/rn5qmqxnv4w5-so...,· 0 - 1 Yrs of Exp,Remote
1,Full Stack .NET Developer – AI-Assisted Develo...,Roaya -,"Maadi, Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/l7avtmywmfxg-full-s...,· 0 - 1 Yrs of Exp,On-site
2,"AI & API Integration Developer (Full-Time, Rem...",iBrokerage Ltd. -,"Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/izzdd2byxhfw-ai-api...,· 3 - 5 Yrs of Exp,Remote
3,Senior AI / Backend Engineer – Technical Lead ...,Confidential -,"Kuwait City, Kuwait",Full Time,(https://wuzzuf.net/jobs/p/eghcexks7ptv-senior...,· 5 - 10 Yrs of Exp,Hybrid
4,AI & Business Process Transformation Manager,Luxury Hospitality -,"6th of October, Giza, Egypt",Full Time,(https://wuzzuf.net/jobs/p/7odmfeuocw2j-ai-bus...,· 3 - 7 Yrs of Exp,On-site
...,...,...,...,...,...,...,...
206,Protection Control & Scada Engineers,National Electricity Technology Co. -,"Bourj Alarab, Alexandria, Egypt",Full Time,(https://wuzzuf.net/jobs/p/iahqxidnnwwq-protec...,· 3 - 5 Yrs of Exp,On-site
207,Civil Site Engineer,Eamar Al Delta -,"Tanta, Gharbia, Egypt",Full Time,(https://wuzzuf.net/jobs/p/lp0yz51lehcq-civil-...,· 5 - 8 Yrs of Exp,On-site
208,Pre Sales Engineer - Financial Sector,Romoze Egypt -,"New Cairo, Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/bgzruidtzqip-pre-sa...,· 3 - 7 Yrs of Exp,Hybrid
209,Architect design and technical office engineer,NEW JERSEY Developments -,"New Cairo, Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/ifqfge4jde0i-archit...,· 3 - 7 Yrs of Exp,On-site
210,Technical Support / Application Support Engineer,eVision -,"New Cairo, Cairo, Egypt",Full Time,(https://wuzzuf.net/jobs/p/8xt2fry7ev52-techni...,· 0 - 2 Yrs of Exp,On-site

In [ ]:
df.isna().sum()# all of our Data is CLean

Job_title         0
Company           0
Location          0
Job_Type          0
Job_URL           0
Job Experience    0
job occupation    0
dtype: int64

In [26]:
df.dtypes

Job_title            str
Company              str
Location             str
Job_Type             str
Job_URL           object
Job Experience    object
job occupation       str
dtype: object

In [27]:

# Save to CSV
df.to_csv("Wuzzuf_Jobs.csv", index=False)

print("Saved successfully!")

Saved successfully!